<?php
return array(
	//'配置项'=>'配置值'

		// 定义数据库连接信息
		'DB_TYPE'=> 'mysql', // 指定数据库是 mysql
		'DB_HOST'=> 'localhost',
		'DB_NAME'=>'myapp', // 数据库名
		'DB_USER'=>'xxyh',
		'DB_PWD'=>'xxyh', //您的数据库连接密码
		'DB_PORT'=>'3306',

		'DB_PREFIX'=>'tp_',//数据表前缀（与数据库myapp 中的表t_users 对应）
		'DISPATCH_ON'=> true, // 该参数设置是否启用 Dispatcher 功能。
		'URL_MODEL' => 2,
		'LOG_RECORD' => true, // 开启日志记录
		'LOG_LEVEL'  =>'EMERG,ALERT,CRIT,ERR,WARN,INFO,DEBUG', // 只记录EMERG ALERT CRIT ERR 错误

		'SESSION_AUTO_START' => true, //是否开启session
		'URL_ROUTER_ON'   => true, //开启路由
		'URL_ROUTE_RULES' => array( //定义路由规则
				'test'=>'Index/test',//系统首页
			 'index'=>'Index/index',//系统首页
			 'main'=>'Index/main',//系统首页
			 'indexproduct'=>'Product/getIndexProduct',//前台产品信息
			 'gologin'=>'Index/goLogin',//跳转登录页面
			 'goregist'=>'Index/goRegist',//跳转注册页面
			 'code'=>'Index/getCode',//获取图片验证码
			 'login'=>'Index/login',//登录
			 'indexnews'=>'News/getIndexNews',//首页文章
			 'userinfo'=>'User/getUserInfo',//用户信息
			 'saveuser'=>'User/saveUserInfo',//更新用户信息
			  'exit'=>'Index/goexit',//退出
			 'usermanager'=>'User/userManager',//用户管理
			 'rolemanager'=>'User/roleManager',//角色管理
			  'menumanager'=>'User/menuManager',//菜单管理
			  'producttype'=>'Product/productTypeList',//产品分类管理
			  'productlist'=>'Product/getProductList',//产品管理
			   'newstype'=>'News/getNewTypeList',//产品管理
			   'newslist'=>'News/getNewsList',//产品管理
				'customerform'=>'Customer/getRecordList',//报单中心
				'addcustomerform'=>'Customer/saveCustomerForm',//报单
				'checkcustomerform'=>'Customer/getAllRecordList',//报单
				'checkform'=>'Customer/changeCustomerForm',//报单
				'contact'=>'User/getContactList',//联系人
				'deletecontact'=>'User/deleteContact',//联系人
				'newcontact'=>'User/AddContact',//联系人
				'gonewcontact'=>'User/goAddContact',//联系人
				'addprotype'=>'Product/addProductType',//联系人vv
				'deleteprotype'=>'Product/deleteProductType',//联系人
				'changeproenabled'=>'Product/changeProductEnabled',//联系人
				'goaddpro'=>'Product/goAddProduct',//联系人
				'newproduct'=>'Product/addNewProduct',//联系人
				'deleteproduct'=>'Product/deleteAllProduct',//联系人
				'deletenewstype'=>'News/deleteAllNewsType',//联系人
				'deletenews'=>'News/deleteAllNews',//联系人
				'addnewstype'=>'News/addNewType',
				'goaddnews'=>'News/goAddNews',
				'savenews'=>'News/addNews',
				'changenews'=>'News/changeNewsEnabled',
				'productinfo'=>'Product/getProductInfo',
				'addShop'=>'Product/AddShopCart',
				'deleteuser'=>'User/deleteAllUser',
				'goadduser'=>'User/goAddUser',
				'newsinfo'=>'News/getNewsInfo',
				'adduser'=>'User/addUserInfo',
				'changeuser'=>'User/changeUserInfo',
				'menumanager'=>'User/getAllMenuList',
				'menutree'=>'User/getMenuTree',
				'changepower'=>'User/changeUserPower',
				'rolemenu'=>'User/getRoleMenu',
				'usermenu'=>'User/getUserMenu',
				'userinfoedit'=>'User/getUserInfoEdit',
				'getmoney'=>'User/checkGetMoney',
				'mychild'=>'User/getAllByChild',
				'gomychild'=>'User/goGetMyChild',
				'addpayinfo'=>'User/addUserPayInfo',
				'goaddpayinfo'=>'User/goUserPayInfo',
				'mypayinfo'=>'User/getMyPayInfo',
				'goupdatepass'=>'User/goUserUpdatePass',
				'updatepass'=>'User/updateUserPass',
				'allpayinfo'=>'User/getAllPayInfo',
				'updatepayinfo'=>'User/updatePayInfoStatus',
				'goaddmyuser'=>'User/goAddMyUser',
				'addmyuser'=>'User/addMyUser',
				'goadduserrole'=>'User/goAddUserRole',
				'adduserrole'=>'User/adduserrole',
				'getmychild'=>'User/getMyChild',
				'calcmoney'=>'User/calcPayMoney',
				'companymanager'=>'User/getCompanyManager',
				'goaddcompany'=>'User/goAddCompanyInfo',
				'newcompany'=>'User/addCompanyInfo',
				'companyinfo'=>'User/getCompanyInfo',
				'deletecompany'=>'User/deleteCompanyInfo',
				'addformapp'=>'User/addFormApp',
				'allformapp'=>'Customer/getAllFormAPPList',
				'changeformapp'=>'Customer/changeFormAppStatus',
				'ticheng'=>'Customer/getPayLogList',
				'allticheng'=>'Customer/getAllPayLogList',
				'getbalancemoney'=>'User/getBalanceMoney',
				'loginlog'=>'Log/getLoginLog',
				'operlog'=>'Log/getOperLog',
				'changemenu'=>'User/changeMenuEnabled',
				'deletemenus'=>'User/deleteMenu',
				'goaddmenu'=>'User/goAddMenu',
				'addmenu'=>'User/addMenu',
				'checkloginname'=>'User/checkLoginName',
				'checkname'=>'User/checkName',
				'alltixian'=>'User/getAllTiXian',
				'updatetixian'=>'User/UpdateTiXian',
				'mytixian'=>'User/getMyTiXian',
				'adddatatype'=>'User/addDatatype',
				'adddata'=>'User/addDatavalue',
				'deletedatatype'=>'User/deleteDatatype',
				'deletedata'=>'User/deletData',
				'data'=>'User/dataManager',
				'goaddtype'=>'User/goAddDataType',
				'goadddata'=>'User/goAddData',
				'updatedata'=>'User/changeData',
				'decodeData'=>'Test/testDecode'

			)
);
?>